# Generated by Django 5.1.5 on 2025-01-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
