# Generated by Django 5.1.5 on 2025-01-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
